### ISSUE TITLE
Before running npm install --save java. Please install Visual Studio 2019 from https://visualstudio.microsoft.com/ first, and check the desktop development using c++.

### ISSUE THREAD

**Issue by zdu-strong** [naxmefy/node-jdbc#16]
![install_java](https://user-images.githubusercontent.com/48673442/126929517-031eff29-8fae-4fc7-a4fb-e82979f88bf2.jpg)

**Comment by zdu-strong** [comment]
It's really amazing, I created my own database.

**Comment by naxmefy** [comment]
@zdu-strong Added the info to a wiki page

https://github.com/naxmefy/node-jdbc/wiki/Install-on-Windows
