### ISSUE TITLE
Query is being blocked by another query

### ISSUE THREAD

**Issue by Tomas2D** [naxmefy/node-jdbc#20]
Hello, firstly I want to thank you for this library, it is well written and suits my needs. I appreciate it.

However, I noticed that when I query running for a long time (say one minute), and I try to run another query, it waits until the first query is resolved.

Is there any chance to run parallels queries, or it is the limitation of the underlying java bindings?

**Comment by naxmefy** [comment]
I dont work active on this project - just did it aside.

May you create a pr by yourself for concurrent querying?

**EDIT**:
maybe you could provide an example?

**Comment by Tomas2D** [comment]
Example is following:
1) run select query A (will finish in 60 seconds)
2) run select query B (will finish in 65 seconds)

... running single query B without running A take 5 seconds.

It looks like, that because of one connection, the second query waits for execution probably.

**Comment by naxmefy** [comment]
did you test it with a second connection? Could a connection pool be a solution?

**Comment by joseederangojr** [comment]
> did you test it with a second connection? Could a connection pool be a solution?

Yes a connection pool would work, its the default behavior of https://github.com/CraZySacX/node-jdbc - https://github.com/CraZySacX/node-jdbc/blob/master/lib/pool.js

**Comment by Tomas2D** [comment]
@joseederangojr your mentioned project blocks (in my case) the event loop, once the query is being executed. I do not recommend it.

**Comment by Tomas2D** [comment]
@naxmefy I solved that issue, by creating multiple child processes which I send commands to. 
This solution is satisfying for me.
