### ISSUE TITLE
is there any way to add jar file in the main.js file

### ISSUE THREAD

**Issue by gopal1996** [naxmefy/node-jdbc#9]
Hi,
I need to retrive data from denodo database. It have only JDBC jar files.
I dont have any maven dependencies.. Is there any possible way to add JAR files explicitly in index file instead of package.json file?

Thanks in advance

**Comment by tonycaohs** [comment]
You could try 'addClasspath'.

import {JDBC, ResultSet, Statement, Java} from '@naxmefy/jdbc';

const jv = new Java(true, false);
jv.addClasspath([ './drivers/hsqldb.jar']);

**Comment by gopal1996** [comment]
Thank You. Its Working :)
